import type { Metadata } from "next";
import Involve from "next/font/local";
import "./globals.css";
import Navbar from "./navbar";

const involve = Involve({
      src: "../../public/Involve-Regular.otf",
    },);

export const metadata: Metadata = {
  title: "Genso",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={involve.className}>
        <div className="min-h-screen">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
